### ISSUE TITLE
TypeError: this.getData is not a function

### ISSUE THREAD

**Issue by AlexWayfer** [remarkjs/remark#1233]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Something indirect, probably new versions of `remark-parse` due to logs

### Steps to reproduce

I've received `remark-cli` and `remark-gfm` (doesn't matter I guess) from Depfu.

And I've noticed fails in Cirrus CI.

In this project were no fails in PRs, but they become after manual push to the `main`:
https://cirrus-ci.com/task/6402074150174720?logs=lint#L12

In this project are fails in PRs:
https://github.com/AlexWayfer/flame-sentry_context/pull/6

I had no errors locally, so I believe it depends on `package-lock.json` (and CI cache).

I've saved the old lock file: (oh, thanks GitHub, JSON files are too dangerous for you) 
[package-lock.json.old.zip](https://github.com/remarkjs/remark/files/12664491/package-lock.json.old.zip)

And after `npm update` I've got the error locally, the `package-lock.json` is here: 
[package-lock.json.zip](https://github.com/remarkjs/remark/files/12664495/package-lock.json.zip)

Node.js v20.7.0, npm v10.1.0 (there are no new versions in your issue template)

### Expected behavior

No errors from indirect dependencies.

### Actual behavior

There is error:

```
> remark -f .
CHANGELOG.md
: no issues found
LICENSE.md
: no issues found
README.md
error
Cannot process file
[cause]
:
    TypeError: this.getData is not a function
    at Object.exitCodeText (file:///tmp/cirrus-ci-build/node_modules/mdast-util-gfm-table/lib/index.js:121:12)
    at compile (file:///tmp/cirrus-ci-build/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:337:40)
    at fromMarkdown (file:///tmp/cirrus-ci-build/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:173:27)
    at parser (file:///tmp/cirrus-ci-build/node_modules/remark-parse/lib/index.js:33:12)
    at Function.parse (file:///tmp/cirrus-ci-build/node_modules/unified/lib/index.js:668:12)
    at parse (file:///tmp/cirrus-ci-build/node_modules/unified-engine/lib/file-pipeline/parse.js:59:36)
    at wrapped (file:///tmp/cirrus-ci-build/node_modules/trough/index.js:115:27)
    at next (file:///tmp/cirrus-ci-build/node_modules/trough/index.js:65:23)
    at done (file:///tmp/cirrus-ci-build/node_modules/trough/index.js:148:7)
    at file:///tmp/cirrus-ci-build/node_modules/unified-engine/lib/file-pipeline/read.js:49:7
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Update both projects at the same time and it should work right now.

It takes time to go through the ecosystem. Wait a bit for the dust to settle :)

**Comment by AlexWayfer** [comment]
Nevermind, I've somehow messed up and there actually was `remark-gfm` v3, not v4. My bad, sorry.

**Comment by wooorm** [comment]
No worries! :)
