### ISSUE TITLE
 Error: Could not find module `preset-lint-markdown-style-recommended`

### ISSUE THREAD

**Issue by chrisfilo** [remarkjs/remark#361]
### Subject of the issue

Unable to use presets and plugins

### Your environment

*   Windows 10 and Linux
*   remark-cli@5.0.0 remark-lint@6.0.2 remark-preset-lint-recommended@3.0.2
*   node@10.8.0 npm@6.4.1

### Steps to reproduce
Following https://github.com/remarkjs/remark/tree/master/packages/remark-cli#usage

```
npm install -g remark-cli@5.0.0 remark-lint@6.0.2 remark-preset-lint-recommended@3.0.2
remark src/*.md src/*/*.md --use preset-lint-markdown-style-recommended
```

See: https://travis-ci.com/bids-standard/bids-specification/builds/86814507

### Expected behaviour

Syntax validation output.

### Actual behaviour

```
  1:1  error  Error: Could not find module `preset-lint-markdown-style-recommended`
    at addModule (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:232:35)
    at use (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:202:7)
    at addIn (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:196:7)
    at addPreset (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:167:9)
    at merge (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:151:5)
    at Config.create (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:109:3)
    at done (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:79:25)
    at apply (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:176:7)
    at applyAll (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:166:7)
    at found (/home/travis/.nvm/versions/node/v10.11.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:158:7)
```

**Comment by wooorm** [comment]
Hmm, weird. It should work. Maybe Travis is being weird or changed something?
The easiest fix is to not install stuff globally. You can install these locally and it would work as well!
I suggest setting stuff up in a `package.json` as well, for example, [take this one](https://github.com/syntax-tree/unist/blob/master/package.json), because then you can run the same stuff locally as on travis.

**Comment by chrisfilo** [comment]
Thanks for your reply.

I don't think it's Travis weirdness - I experienced the same issue on a
non-travis machine.

I also tried a local install, but I'm still getting the same error when
using the --use flag.

I'll try package.json (although technically speaking the project I'm using
this for is not a JavaScript project).

**Comment by chrisfilo** [comment]
That worked - thanks!

Best,
Chris
