### ISSUE TITLE
Error: Incorrectly eaten value

### ISSUE THREAD

**Issue by APixelVisuals** [remarkjs/remark#463]
### Incorrectly eaten value

I got an error while [extending the `remark-parse` parser](https://www.npmjs.com/package/remark-parse#extending-the-parser):

```
Error: Incorrectly eaten value: please report this warning on https://git.io/vg5Ft
    at validateEat (/home/apixel/Documents/project/node_modules/remark-parse/lib/tokenizer.js:147:11)
    at eat (/home/apixel/Documents/project/node_modules/remark-parse/lib/tokenizer.js:232:7)
    at Of.remarkParse.Parser.inlineTokenizers.userTag (/home/apixel/Documents/project/modules/misc/Image.js:12:28)
    at Of.tokenize [as tokenizeInline] (/home/apixel/Documents/project/node_modules/remark-parse/lib/tokenizer.js:58:18)
    at Of.paragraph (/home/apixel/Documents/project/node_modules/remark-parse/lib/tokenize/paragraph.js:115:20)
    at Of.tokenize [as tokenizeBlock] (/home/apixel/Documents/project/node_modules/remark-parse/lib/tokenizer.js:58:18)
    at Of.parse (/home/apixel/Documents/project/node_modules/remark-parse/lib/parse.js:33:20)
    at Function.parse (/home/apixel/Documents/project/node_modules/unified/index.js:271:45)
    at Image.markdownText (/home/apixel/Documents/project/modules/misc/Image.js:94:36)
    at module.exports (/home/apixel/Documents/project/modules/messageImage.js:45:36)
```

### Environment

*   **OS**: Linux Mint 19.1 Cinnamon
*   **Packages**: `remark-parse` v7.0.2, `unified` v8.4.2
*   **Env**: Node.js v10.18.0, NPM v6.13.4

### Steps to reproduce

```
const remarkParse = require("remark-parse");

remarkParse.Parser.prototype.inlineTokenizers.userTag = (eat, value, silent) => {

    const match = /<@!?[0-9]+>/.exec(value);

    if ((match) && (silent)) return true;
    else if (match) return eat(match[0])({
        type: "userTag",
        children: [{ type: "text", value: match[0].replace(/<>@!/g, "") }],
    });
};
remarkParse.Parser.prototype.inlineTokenizers.userTag.locator = (value, fromIndex) => value.indexOf("<", fromIndex);
remarkParse.Parser.prototype.inlineMethods.splice(remarkParse.Parser.prototype.inlineMethods.indexOf("text"), 0, "userTag");

const markdownParser = require("unified")().use(remarkParse);

markdownParser.parse("asd asd <@!196795781410324480> asdasd")
```

### Expected behavior

`<@!196795781410324480>` should be parsed as a `userTag`.

### Actual behavior

I get the error above.

**Comment by APixelVisuals** [comment]
Misclicked, sorry

**Comment by ChristianMurphy** [comment]
@APixelVisuals the value is correctly eaten, you need guard statements to ensure the value you are looking for matches your expected pattern.
See https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/html-inline.js for an example.

In your case the guard could look something like:

```
if (
  value.charAt(0) !== "<" ||
  value.charAt(1) !== "@" ||
  value.charAt(2) !== "!" ||
  value.length < 5
) {
  return;
}
```

add it anywhere before `eat` is called.

**Comment by APixelVisuals** [comment]
Thanks for the help, everything is working fine now.
