### ISSUE TITLE
Footnote with trailing newline and space throws "Incorrectly eaten value"

### ISSUE THREAD

**Issue by kevinansfield** [remarkjs/remark#468]
### Subject of the issue

When parsing markdown with footnotes enabled, if the last footnote is followed by a newline and any spaces it throws an error.

### Your environment

*   **OS**: macOS 10.15.3, also seen on our production Ubuntu servers
*   **Packages**: `remark@11.0.1`, `remark-parse@7.0.2`
*   **Env**: node v10.16.0

### Steps to reproduce

Minimal reproduction:

```javascript
const remark = require('remark')
const markdown = '[^1]: Footnote with trailing newline and space\n ';
remark().use({settings: {commonmark: true, footnotes: true}}).parse(markdown);
```

```
➜ node
> const remark = require('remark')
> const markdown = '[^1]: Footnote with trailing newline and space\n ';
> remark().use({settings: {commonmark: true, footnotes: true}}).parse(markdown);
Thrown:
{ Error: Incorrectly eaten value: please report this warning on https://git.io/vg5Ft
    at validateEat (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenizer.js:147:11)
    at eat (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenizer.js:232:7)
    at Of.footnoteDefinition (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenize/footnote-definition.js:174:9)
    at Of.tokenize [as tokenizeBlock] (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenizer.js:58:18)
    at Of.parse (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/parse.js:33:20)
    at Function.parse (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/unified/index.js:271:45)
    at repl:1:63
    at Script.runInThisContext (vm.js:122:20)
    at REPLServer.defaultEval (repl.js:332:29)
    at bound (domain.js:402:14)
  stack:
   'Error: Incorrectly eaten value: please report this warning on https://git.io/vg5Ft\n    at validateEat (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenizer.js:147:11)\n    at eat (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenizer.js:232:7)\n    at Of.footnoteDefinition (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenize/footnote-definition.js:174:9)\n    at Of.tokenize [as tokenizeBlock] (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/tokenizer.js:58:18)\n    at Of.parse (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/remark-parse/lib/parse.js:33:20)\n    at Function.parse (/Users/kevinansfield/code/ghost/Ghost-SDK/node_modules/unified/index.js:271:45)\n    at repl:1:63\n    at Script.runInThisContext (vm.js:122:20)\n    at REPLServer.defaultEval (repl.js:332:29)\n    at bound (domain.js:402:14)',
  message:
   'Incorrectly eaten value: please report this warning on https://git.io/vg5Ft',
  name: '1:1',
  reason:
   'Incorrectly eaten value: please report this warning on https://git.io/vg5Ft',
  line: 1,
  column: 1,
  location:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: null, column: null } },
  source: null,
  ruleId: null,
  fatal: true }
```

### Expected behaviour

Markdown is parsed without error as it is when the trailing space is removed.

### Actual behaviour

Throws error `'Error: Incorrectly eaten value: please report this warning on https://git.io/vg5Ft'`

**Comment by wooorm** [comment]
Hmmm that’s definitely a bug, probably somewhere [here](https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/footnote-definition.js)! Thanks for noticing.
