### ISSUE TITLE
Error: Cannot handle unknown node `table`

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark#543]
Getting this error using latest version of all remark plugins, CLI, etc. (I'm working locally and version bumped _everything_ to latest).

```sh
README.md
  1:1  error  Error: Cannot handle unknown node `table`
    at Object.unknown (/Users/user/Projects/eslint-config-xo-lass/node_modules/mdast-util-to-markdown/lib/index.js:52:9)
    at Object.one [as handle] (/Users/user/Projects/eslint-config-xo-lass/node_modules/zwitch/index.js:20:25)
    at flow (/Users/user/Projects/eslint-config-xo-lass/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:18:15)
    at root (/Users/user/Projects/eslint-config-xo-lass/node_modules/mdast-util-to-markdown/lib/handle/root.js:6:10)
    at one (/Users/user/Projects/eslint-config-xo-lass/node_modules/zwitch/index.js:20:25)
    at toMarkdown (/Users/user/Projects/eslint-config-xo-lass/node_modules/mdast-util-to-markdown/lib/index.js:25:16)
    at compile (/Users/user/Projects/eslint-config-xo-lass/node_modules/remark-stringify/index.js:13:12)
    at Function.stringify (/Users/user/Projects/eslint-config-xo-lass/node_modules/unified/index.js:354:12)
    at stringify (/Users/user/Projects/eslint-config-xo-lass/node_modules/unified-engine/lib/file-pipeline/stringify.js:45:23)
    at wrapped (/Users/user/Projects/eslint-config-xo-lass/node_modules/trough/wrap.js:25:19)
```

**Comment by ChristianMurphy** [comment]
@niftylettuce please fill out the issue template https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md
It provides the context we need in order to help.

**Comment by ChristianMurphy** [comment]
Also if you recently upgrade to latest, please see the release notes: https://github.com/remarkjs/remark/releases/tag/13.0.0
in particular:
> Did you use GFM (tables and so, used to be the default)? Now add `remark-gfm`

**Comment by niftylettuce** [comment]
I've narrowed it down to `remark-contributors` being the issue (have had a lot of issues with this package over time).

https://github.com/remarkjs/remark-contributors

**Comment by wooorm** [comment]
@niftylettuce Please do not remove issue templates: I can understand newcomers forgetting that but you have significant experience here on GH. The answer you are looking for is as Christian pointed out documented in the [migration section on the release notes](https://github.com/remarkjs/remark/releases/tag/13.0.0).

**Comment by niftylettuce** [comment]
@wooorm I think it has to do with this https://github.com/syntax-tree/mdast-util-to-markdown/issues/1 from what I can see.  I tried adding this to the `index.js` of the example repo linked above and it still fails with the same output:

```js
[ unified().use(gfm), require('remark-contributors') ]
```

I will be sure to not remove template moving forwards, sorry about that, definitely noted.  If there's any pointers you could share to help me debug this further let me know, it's been a while since I last looked at all this remark plugin/ecosystem.  I looked at the source and came up with that issue linked as basically the same issue I face.

**Comment by wooorm** [comment]
@milahu It seems you have not read the thread. You should use `remark-gfm` to enable GFM extensions that are not in standard markdown.

**Comment by milahu** [comment]
i want to produce "strict markdown" with html tables, so `remark-gfm` does not help

the error message is a bit obscure to a unifiedjs noob like me, so im sharing my solution here

**Comment by wooorm** [comment]
Okay! The main solution to this error that I believe most folks are looking for when they stumble here, is: use `remark-gfm`, as it handles table nodes.

If you don’t want GFM, your solution works (as you note, not all HTML can be represented in markdown though). For more info, see: https://github.com/rehypejs/rehype-remark#example-keeping-some-html.
